apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpress-app-post-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpress-app-post-service
  template:
    metadata:
      labels:
        app: kpress-app-post-service
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z kpress-db-post 5431; do echo waiting for database; sleep 2; done;']
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z kpress-rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;']
      containers:
        - name: kpress-app-post-service
          image: iru44/kpress-app-post-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3032
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"