apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpress-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpress-db
  template:
    metadata:
      labels:
        app: kpress-db
    spec:
      containers:
        - name: kpress-db
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: "myuser"
            - name: POSTGRES_PASSWORD
              value: "mypassword"
            - name: POSTGRES_DB
              value: "mydb"
          ports:
            - containerPort: 5432
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
