apiVersion: v1
kind: Service
metadata:
  name: kpress-k8s-app
spec:
  type: LoadBalancer
  selector:
    app: kpress-k8s-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3030

---
apiVersion: v1
kind: Service
metadata:
  name: kpress-db
spec:
  type: ClusterIP
  selector:
    app: kpress-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
