apiVersion: v1
kind: Service
metadata:
  name: kpress-app-gateway-service
spec:
  type: LoadBalancer
  selector:
    app: kpress-app-gateway-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: kpress-app-todo-service
spec:
  type: LoadBalancer
  selector:
    app: kpress-app-todo-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 3031
---
apiVersion: v1
kind: Service
metadata:
  name: kpress-app-post-service
spec:
  type: LoadBalancer
  selector:
    app: kpress-app-post-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 3032
---
apiVersion: v1
kind: Service
metadata:
  name: kpress-app-user-service
spec:
  type: LoadBalancer
  selector:
    app: kpress-app-user-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 3033
---
apiVersion: v1
kind: Service
metadata:
  name: kpress-db-user
spec:
  type: ClusterIP
  selector:
    app: kpress-db-user
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5433
---
apiVersion: v1
kind: Service
metadata:
  name: kpress-db-post
spec:
  type: ClusterIP
  selector:
    app: kpress-db-post
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5431
---
apiVersion: v1
kind: Service
metadata:
  name: kpress-db-todo
spec:
  type: ClusterIP
  selector:
    app: kpress-db-user
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5434
---
apiVersion: v1
kind: Service
metadata:
  name: kpress-app-frontend
spec:
  type: LoadBalancer
  selector:
    app: kpress-app-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: grafana
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: prometheus